In [ ]:
import numpy as np
from copy import copy, deepcopy

In [16]:
def simulation(X):
  X = np.array(X)
  matrices_list = []
  matrices_list.append(X)

  y_true = [[1,2,3],[4,5,6],[7,8,0]]
  y_true = np.array(y_true)

  linha, coluna = findZero(X)
  print("Jogo Inicial:\n",X)
  print("\nZero Inicial ->\tLinha:",linha,"Coluna:",coluna,"\n-----------------------------------------")

  if ((X==y_true).all())==True:
    print("Jogo Finalizado!")
  else:
    it=0
    for i in range(1000000):
      if search(matrices_list, y_true)==True:
        print("Jogo Finalizado!")  
        #print("Sequencia: \n",matrices_list)
        print("Iterações: \n",it)
        return
      else:
        it+=1
        switch([linha,coluna],matrices_list[i],matrices_list)

def search(list, matrix):
    for i in range(len(list)):
        if ((list[i]==matrix).all()):
            return True
    return False

def isEqual_y_true(matrix):
    y_true = [[1,2,3],[4,5,6],[7,8,0]]
    y_true = np.array(y_true)
    if ((y_true==matrix).all()):
        return True
    return False

def findZero(X):
  linha,coluna = np.where(X==0)
  linha = linha[0]
  coluna = coluna[0]
  return linha,coluna

def moveRight(X):
  linha, coluna = findZero(X)
  if coluna != 2:
    aux = X[linha,coluna+1]
    X[linha,coluna+1] = 0
    X[linha,coluna] = aux
  return X

def moveLeft(X):
  linha, coluna = findZero(X)
  if coluna != 0:
    aux = X[linha,coluna-1]
    X[linha,coluna-1] = 0
    X[linha,coluna] = aux
  return X

def moveDown(X):
  linha, coluna = findZero(X)
  if linha != 2:
    aux = X[linha+1,coluna]
    X[linha+1,coluna] = 0
    X[linha,coluna] = aux
  return X

def moveUp(X):
  linha, coluna = findZero(X)
  if linha != 0:
    aux = X[linha-1,coluna]
    X[linha-1,coluna] = 0
    X[linha,coluna] = aux
  return X

def switch(pos,X,matrices_list):
    if pos == [0,0]:
      X1 = deepcopy(X)
      X1 = moveRight(X1)
      X2 = deepcopy(X)
      X2 = moveDown(X2)
      if isEqual_y_true(X1)==True or isEqual_y_true(X2)==True:
        print("Jogo Finalizado!")
        return
      matrices_list.extend([X1,X2])
    elif pos == [0,1]:
      X1 = deepcopy(X)
      X2 = deepcopy(X)
      X3 = deepcopy(X)
      X1 = moveRight(X1)
      X2 = moveDown(X2)
      X3 = moveLeft(X3)
      matrices_list.extend([X1,X2,X3])
    elif pos == [0,2]:
      X1 = deepcopy(X)
      X2 = deepcopy(X)
      X1 = moveDown(X1)
      X2 = moveLeft(X2)
      matrices_list.extend([X1,X2])
    elif pos == [1,0]:
      X1 = deepcopy(X)
      X2 = deepcopy(X)
      X3 = deepcopy(X)
      X1 = moveRight(X1)
      X2 = moveDown(X2)
      X3 = moveUp(X3)
      matrices_list.extend([X1,X2,X3])
    elif pos == [1,1]:
      X1 = deepcopy(X)
      X2 = deepcopy(X)
      X3 = deepcopy(X)
      X4 = deepcopy(X)
      X1 = moveRight(X1)
      X2 = moveDown(X2)
      X3 = moveLeft(X3)
      X4 = moveUp(X4)
      matrices_list.extend([X1,X2,X3,X4])
    elif pos == [1,2]:
      X1 = deepcopy(X)
      X2 = deepcopy(X)
      X3 = deepcopy(X)
      X1 = moveDown(X1)
      X2 = moveLeft(X2)
      X3 = moveUp(X3)
      matrices_list.extend([X1,X2,X3])
    elif pos == [2,0]:
      X1 = deepcopy(X)
      X2 = deepcopy(X)
      X1 = moveUp(X1)
      X2 = moveRight(X2)
      matrices_list.extend([X1,X2])
    elif pos == [2,1]:
      X1 = deepcopy(X)
      X2 = deepcopy(X)
      X3 = deepcopy(X)
      X1 = moveRight(X1)
      X2 = moveLeft(X2)
      X3 = moveUp(X3)
      matrices_list.extend([X1,X2,X3])
    elif pos == [2,2]:
      X1 = deepcopy(X)
      X2 = deepcopy(X)
      X1 = moveLeft(X1)
      X2 = moveUp(X2)
      matrices_list.extend([X1,X2])
    return

In [ ]:
arr = np.arange(9)
arr = np.random.permutation(arr)
arr = arr.reshape((3,3))
print(arr)

[[0 6 7]
 [3 2 8]
 [4 1 5]]


In [ ]:
simulator = simulation(arr)

In [15]:
#X_teste = [[1,2,3],[4,5,6],[7,8,0]]
#X_teste = [[1,2,3],[4,5,6],[7,0,8]]
X_teste = [[1,2,3],[4,0,8],[7,6,5]]
    
simulator = simulation(X_teste)

Jogo Inicial:
 [[1 2 3]
 [4 0 8]
 [7 6 5]]

Zero Inicial ->	Linha: 1 Coluna: 1 
-----------------------------------------
Jogo Finalizado!
Sequencia: 
 [array([[1, 2, 3],
       [4, 0, 8],
       [7, 6, 5]]), array([[1, 2, 3],
       [4, 8, 0],
       [7, 6, 5]]), array([[1, 2, 3],
       [4, 6, 8],
       [7, 0, 5]]), array([[1, 2, 3],
       [0, 4, 8],
       [7, 6, 5]]), array([[1, 0, 3],
       [4, 2, 8],
       [7, 6, 5]]), array([[1, 2, 3],
       [4, 8, 0],
       [7, 6, 5]]), array([[1, 2, 3],
       [4, 8, 5],
       [7, 6, 0]]), array([[1, 2, 3],
       [4, 0, 8],
       [7, 6, 5]]), array([[1, 2, 0],
       [4, 8, 3],
       [7, 6, 5]]), array([[1, 2, 3],
       [4, 6, 8],
       [7, 5, 0]]), array([[1, 2, 3],
       [4, 6, 8],
       [7, 0, 5]]), array([[1, 2, 3],
       [4, 6, 8],
       [0, 7, 5]]), array([[1, 2, 3],
       [4, 0, 8],
       [7, 6, 5]]), array([[1, 2, 3],
       [4, 0, 8],
       [7, 6, 5]]), array([[1, 2, 3],
       [7, 4, 8],
       [0, 6, 5]]), array([